# Enable Mediapipe Solutions
enable_right_hand: true
enable_left_hand: true
enable_pose: true
enable_face: false

# Training Parameters
min_epochs: 30
max_epochs: 500
min_delta: 0.01
patience: 20
batch_size: 128
optimizer: AdamW
learning_rate: 1e-4
loss_function: cross_entropy
train_set_size: 0.8
validation_set_size: 0.1
test_set_size: 0.1

# Torch Compilation
compilation_mode: default
torch_compilation: false
profiler: false
fast_dev_run: false

hydra:
  run:
    dir: 
      /home/davide/ROS/ros_2_ws/src/Mediapipe/mediapipe_gesture_recognition/data/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
